<?php

namespace Database\Seeders;

use App\Models\Name;
use Illuminate\Database\Seeder;

class NameSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $human_females = [
            "Daria",
            "Emilia",
            "Helga",
            "Kaela",
            "Kaylee",
            "Maya",
            "Melody",
            "Nera",
            "Reyanna",
        ];

        $elven_females = [
            "Aelene",
            "Aelinor",
            "Aemma",
            "Akash",
            "Alaesa",
            "Alaglossa",
            "Alais",
            "Alauthshae",
            "Alavara",
            "Alea",
            "Alerathla",
            "Allannia",
            "Alloralla",
            "Alys",
            "Amaryll",
            "Aquilaen",
            "Aredhel",
            "Arwen",
            "Axilia",
            "Ayaeqlarune",
            "Azariah",
            "Baelen",
            "Beala",
            "Bhuraelea",
            "Blythswana",
            "Bonnalurie",
            "Braerindra",
            "Caerthynna",
            "Calarel",
            "Cauladra",
            "Celebrían",
            "Chandrelle",
            "Chasianna",
            "Chichlandra",
            "Chin’nesstre",
            "Chomylla",
            "Ciyradyl",
            "Daealla",
            "Daena",
            "Daenestra",
            "Daenys",
            "Daeondra",
            "Doreah",
            "Elaria",
            "Elenwe",
            "Ellania",
            "Elora",
            "Elwing",
            "Elyssa",
            "Fhaertala",
            "Filaurel",
            "Filauria",
            "Fildaerae",
            "Finduilas",
            "Fraeya",
            "Gaelira",
            "Gaerradh",
            "Galadriel",
            "Gaylia",
            "Ghilanna",
            "Gilgalad",
            "Glorfindel",
            "Glynnii",
            "Gweyr",
            "Gwynnestri",
            "Gylledha",
            "Haalija",
            "Hacathra",
            "Haela",
            "Halaema",
            "Halaena",
            "Halama",
            "Halanaestra",
            "Hameada",
            "Holcene",
            "Holone",
            "Hycis",
            "Iahalae",
            "Ialantha",
            "Idril",
            "Ikeshia",
            "Ilmadia",
            "Ilyrana",
            "Ilythyrra",
            "Imdalace",
            "Imizael",
            "Irithiel",
            "Ithirae",
            "Iziuel",
            "Jahandra",
            "Kaeda",
            "Kaylessa",
            "Keara",
            "Keerla",
            "Keishara",
            "Kethryllia",
            "Keya",
            "Kyrrha",
            "Kythaela",
            "Laamtora",
            "Laeanna",
            "Laena",
            "Laerdya",
            "Lazziar",
            "Leandra",
            "Leilatha",
            "Liluth",
            "Llamryl",
            "Lorelei",
            "Lúthien",
            "Lyraesel",
            "Maaleshiira",
            "Maegelle",
            "Maelyrra",
            "Maeralya",
            "Mariah",
            "Meara",
            "Mereena",
            "Merlara",
            "Miriel",
            "Morwen",
            "Mylaela",
            "Myrynda",
            "Nuovis",
            "Nushala",
            "Nylaathria",
            "Ochyllyss",
            "Oluevaera",
            "Phaerl",
            "Phantyni",
            "Phelorna",
            "Phuingara",
            "Phyrra",
            "Quaela",
            "Quamara",
            "Raejiisa",
            "Raerauntha",
            "Rathiain",
            "Reinys",
            "Renestrae",
            "Renna",
            "Rubrae",
            "Ryllae",
            "Saelihn",
            "Saélihn",
            "Saeya",
            "Sasha",
            "Shalana",
            "Shalantha",
            "Shalheira",
            "Shandalar",
            "Shanyrria",
            "Sharaera",
            "Sheedra",
            "Shiera",
            "Shyael",
            "Shyllisyrr",
            "Sinnafain",
            "Soliania",
            "Soora",
            "Sorsasta",
            "Susklahava",
            "Sylmae",
            "Symrustar",
            "Syndra",
            "Synnorha",
            "Syrenese",
            "Syrune",
            "Syviis",
            "Taena",
            "Taenya",
            "Taeriel",
            "Takari",
            "Talaedra",
            "Talanashta",
            "Talila",
            "Talilia",
            "Talindra",
            "Tamara",
            "Tarasynora",
            "Teharissa",
            "Tiatha",
            "Tsarra",
            "Tyria",
            "Urmicca",
            "Vaella",
            "Valindra",
            "Veara",
            "Vestele",
            "Viansola",
            "Violen",
            "Viserra",
            "Yaereene",
            "Yalanilue",
            "Yathlanae",
            "Ynshael",
            "Yrlissa",
            "Yrneha",
            "Yrniela",
            "Zeale",
            "Zhuirentel",
        ];

        $dwarven_females = [
            "Aden",
            "Admina",
            "Afra",
            "Agran",
            "Amethyst",
            "Avil",
            "Bari",
            "Barol",
            "Bavol",
            "Bhelkam",
            "Bjarki",
            "Bofar",
            "Bramdahr",
            "Branmand",
            "Brynjolvur",
            "Calgrima",
            "Calona",
            "Calund",
            "Chalia",
            "Chalia",
            "Cosette",
            "Crystal",
            "Dellinger",
            "Demeter",
            "Dhara",
            "Dila",
            "Dilgli",
            "Dithin",
            "Dodur",
            "Dolana",
            "Dora",
            "Dorola",
            "Dovana",
            "Dovli",
            "Dradir",
            "Dravan",
            "Dugrona",
            "Dunora",
            "Eartha",
            "Ebgran",
            "Edmundur",
            "Eiki",
            "Eilivur",
            "Ela",
            "Elindur",
            "Elrfoubelyn",
            "Emorette",
            "Erla",
            "Esmeralda",
            "Fiden",
            "Flintheart",
            "Gagon",
            "Gavil",
            "Gimli",
            "Giva",
            "Givur",
            "Hundairgit",
            "Jade",
            "Lana",
            "Lazuli",
            "Malvan",
            "Montana",
            "Narvi",
            "Randon",
            "Rarona",
            "Reginn",
            "Rudli",
            "Rundir",
            "Sapphire",
            "Sienna",
            "Thortor",
            "Thovir",
            "Thovir",
            "Ula",
        ];

        $human_males = [
            "Angegisis",
            "Agilbert",
            "Cayde",
            "Corey",
            "Daggett",
            "Jackson",
            "Miles",
            "Norbert",
            "Phineas",
            "Prime",
            "Sebastian",
            "Vauziath",
        ];

        $elven_males = [
            "Aego",
            "Aelrindel",
            "Aerendyl",
            "Aeson",
            "Afamrail",
            "Agis",
            "Ailmar",
            "Aithlin",
            "Akkar",
            "Alabyran",
            "Aranel",
            "Arazorwyn",
            "Beleg",
            "Beluar",
            "Biafyndar",
            "Bialaer",
            "Braern",
            "Briareth",
            "Cameron",
            "Celeborn",
            "Celebrimbor",
            "Chathanglas",
            "Cheyrth",
            "Círdan",
            "Cluhurach",
            "Cluym",
            "Cohnal",
            "Conall",
            "Connak",
            "Cornaith",
            "Corym",
            "Curunir",
            "Cymbiir",
            "Cystenn",
            "Daeharice",
            "Daemeon",
            "Dakath",
            "Dalyor",
            "Darcassan",
            "Dior",
            "Earendil",
            "Edrahil",
            "Eladithas",
            "Elanjar",
            "Elaran",
            "Elashor",
            "Elbauthin",
            "Elbereth",
            "Eldaernth",
            "Eldar",
            "Eldrin",
            "Elénaril",
            "Elenshaer",
            "Elrond",
            "Eluchil",
            "Elwin",
            "Erlan",
            "Erlathan",
            "Eroan",
            "Erolith",
            "Eschallus",
            "Estelar",
            "Etchelion",
            "Ethlando",
            "Ettrian",
            "Evindal",
            "Eyrynnhv",
            "Eyrynnhv",
            "Faelar",
            "Faelyn",
            "Faeranduil",
            "Falael",
            "Fëanor",
            "Fenris",
            "Filvendor",
            "Fingolfin",
            "Finrod",
            "Folduin",
            "Gael",
            "Gaemon",
            "Gil-galad",
            "Glynkas",
            "Haemir",
            "Hagduin",
            "Haladavar",
            "Halafarin",
            "Haryk",
            "Hastos",
            "Hatharal",
            "Herbalar",
            "Horith",
            "Hubyr",
            "Iarmenor",
            "Iefyr",
            "Ievos",
            "Ilbryn",
            "Iliven",
            "Ilthuryn",
            "Inarie",
            "Inchel",
            "Inialos",
            "Injros",
            "Intevar",
            "Iolas",
            "Jassin",
            "Jhaan",
            "Jhaartael",
            "Jhaeros",
            "Kelkalyn",
            "Kevan",
            "Klaern",
            "Kolvar",
            "Kuornos",
            "Kuskyn",
            "Kymil",
            "Kyrenic",
            "Kyrtaar",
            "Legolas",
            "",
            "lrune",
            "Maiele",
            "Mithrandir",
            "Molonym",
            "Molostroi",
            "Montagor",
            "Morgan",
            "Morthil",
            "Myrddin",
            "Myriil",
            "Myrin",
            "Mythanthar",
            "Naertho",
            "Naeryndam",
            "Napraeleon",
            "Narbeth",
            "Nardual",
            "Nelaeryn",
            "Neldor",
            "Nerilamin",
            "Nesterin",
            "Nevarth",
            "Nhamashal",
            "Nieven",
            "Nindr",
            "Nym",
            "Onas",
            "Oribel",
            "Oritris",
            "Orndacil",
            "Ornthalas",
            "Orris",
            "Orym",
            "Oslarelar",
            "Otaehryn",
            "Othorion",
            "Paeral",
            "Paeris",
            "Phaendar",
            "Pharom",
            "Phraan",
            "Pirphal",
            "Pleufan",
            "Purtham",
            "Pyrder",
            "Quaeth",
            "Raegel",
            "Raunaeril",
            "Ravaphine",
            "Reysalor",
            "Rhistel",
            "Saelethil",
            "Saevel",
            "Seiveril",
            "Sharian",
            "Siirist",
            "Silvyr",
            "Sudryl",
            "Taenaran",
            "Taerntym",
            "Tamnaeuth",
            "Tannivh",
            "Tassarion",
            "Tehlmar",
            "Therona",
            "Thingol",
            "Thranduil",
            "Toross",
            "Travaran",
            "Triandal",
            "Turgon",
            "Usunaar",
            "Uthorim",
            "Vaalyun",
            "Vaegon",
            "Vaeril",
            "Venrie",
            "Virjeon",
            "Yhendorn",
            "Ylyndar",
            "Zabbas",
            "Zaltarish",
        ];

        $dwarven_males = [
            "Addanc",
            "Aigror",
            "Algir",
            "Anil",
            "Anin",
            "Anvari",
            "Argos",
            "Ari",
            "Avion",
            "Baglia",
            "Bagrna",
            "Ballin",
            "Balthrasir",
            "Bamira",
            "Bargun",
            "Bashful",
            "Bavola",
            "Bes",
            "Bhalkyl",
            "Bhalmun",
            "Bharrom",
            "Bifur",
            "Bilbur",
            "Bofur",
            "Bombur",
            "Bothor",
            "Bovan",
            "Braka",
            "Bramdur",
            "Brand",
            "Brokk",
            "Buboth",
            "Calgak",
            "Calgrima",
            "Chalona",
            "Chirysaor",
            "Cola",
            "Danil",
            "Daremrun",
            "Divira",
            "Dogrila",
            "Dondna",
            "Dopey",
            "Dori",
            "Dothura",
            "Dragrola",
            "Dramola",
            "Draupin",
            "Duvur",
            "Dwomnaed",
            "Ebdrus",
            "Fimbul",
            "Firguc",
            "Galvon",
            "Gandalf",
            "Gidel",
            "Gim",
            "Gloin",
            "Glorgil",
            "Goliath",
            "Grumpy",
            "Hannar",
            "Happy",
            "Huffie",
            "Kibil",
            "Kili",
            "Malgon",
            "Malvon",
            "Nori",
            "Oin",
            "Onfroi",
            "Ruvon",
            "Sneezy",
            "Thondin",
            "Titan",
            "Travaran",
            "Wade",
        ];

        $human_nbs = [
            "Ellis",
            "Kai",
            "Kit",
            "Remy",
            "Rowan",
            "Sage",
            "Sawyer",
            "Zephyr",
        ];

        $elven_nbs = [
            "Vulmon",
        ];

        $dwarven_nbs = [];

        $human_last = [
            "Bates",
            "Chapmyre",
            "Connington",
            "Falker",
            "Knotwise",
            "Lothran",
            "Path",
            "Parren",
            "Sutton",
            "Thuluthea",
            "Walker",
            "Wilkinson",
            "White",
        ];

        $elven_last = [
            "Adanell",
            "Aelasar",
            "Aelorothi",
            "Aendryr",
            "Aerasumé",
            "Aeravansel",
            "Aldaval",
            "Aloiene",
            "Alqualonde",
            "Amaratharr",
            "Amarthen",
            "Ammath",
            "Amrallatha",
            "Anuaer",
            "Ardorius",
            "Artordhron",
            "Augalvaryl",
            "Balstina",
            "Beinion",
            "Beor",
            "Braegen",
            "Briarbosk",
            "Brightcloak",
            "Brightsong",
            "Brightspear",
            "Brightstar",
            "Brightwing",
            "Castien",
            "Caundur",
            "Celelaeth",
            "Cererindur",
            "Chamaranthe",
            "Clatharla",
            "Corellon",
            "Cormyth",
            "Coudoarluth",
            "Craulnober",
            "Crystalis",
            "Cubrinmyr",
            "Darkbrood",
            "Darkcloak",
            "Darkwing",
            "Deryth",
            "Dor-lomin",
            "Dragonrider",
            "Eaglelord",
            "Ealoloth",
            "Ealoviel",
            "Earcorn",
            "Elaéyadar",
            "Elassidil",
            "Elerelwa",
            "Elian",
            "Elkenmage",
            "Ellarian",
            "Elond",
            "Erladden",
            "Erlshade",
            "Eroth",
            "Eruien",
            "Erunonidan",
            "Estelda",
            "Evanara",
            "Faefindas",
            "Faelen",
            "Faenion",
            "Faenor",
            "Faerondalan",
            "Felarathael",
            "Finwe",
            "Floralei",
            "Flyleaf",
            "Frostfang",
            "Gaelen",
            "Galaalta",
            "Goldenleaf",
            "Gourael",
            "Greencloak",
            "Gwaelon",
            "Hadirsyr",
            "Hador",
            "Haell",
            "Haerlgent",
            "Haleth",
            "Hasterien",
            "Hatanar",
            "Helion",
            "Hessarion",
            "Idhtulcdrach",
            "Ievos",
            "Iliathorr",
            "Ilijor",
            "Ilnatar",
            "Immeril",
            "Impanton",
            "Imphenon",
            "Ipyllasc",
            "Irian",
            "Isiliraiellyn",
            "Kadhorduil",
            "Kithsidhion",
            "Kraok",
            "Laedireil",
            "Laelithar",
            "Lannarseer",
            "Laralytha",
            "Larbrinlal",
            "Larenthanil",
            "Larethian",
            "Lashrael",
            "Lassagaseer",
            "Lasslail",
            "Leaadion",
            "Liondale",
            "Lithelon",
            "Lithron",
            "Loramys",
            "Maedhros",
            "Maeglin",
            "Maeir",
            "Maertel",
            "Magor",
            "Maltathdar",
            "Moondown",
            "Moonflower",
            "Moonford",
            "Moonglade",
            "Moonshrine",
            "Moorfly",
            "Nenaias",
            "Nhachashaal",
            "Nhaéslal",
            "Nharimlur",
            "Nightstar",
            "Nightswatch",
            "Nightwing",
            "Noldorin",
            "Norodiir",
            "Northstar",
            "Oaktree",
            "Ongluth",
            "Orama",
            "Orbryn",
            "Quendi",
            "Redwing",
            "Rhothomir",
            "Rhuidhen",
            "Rhyllgallohyr",
            "Rivleam",
            "Rivvikyn",
            "Runemaster",
            "Sarsantyr",
            "Selakiir",
            "Selmer",
            "Shinestar",
            "Shiredove",
            "Silkstream",
            "Siltral",
            "Silverbow",
            "Silverhand",
            "Silveroak",
            "Silverspear",
            "Simserion",
            "Snowfell",
            "Snowreign",
            "Stillhawk",
            "Stilmyst",
            "Stormspear",
            "Straeth",
            "Strongbow",
            "Suldusk",
            "Sunfoal",
            "Sunshield",
            "Sunstar",
            "Sylleth",
            "Tassarion",
            "Tathdel",
            "Taurntyrith",
            "Telerie",
            "Tellynnan",
            "Teshurr",
            "Thalien",
            "Thoimion",
            "Thothiion",
            "Thundruil",
            "Tipantdon",
            "Turnvale",
            "Tyrell",
            "Vanamaeduil",
            "Vanvathar",
            "Vispasial",
            "Voronbund",
            "Vyshaan",
            "Waelvor",
            "Werloththar",
            "Whitethistle",
            "Windslore",
            "Windstar",
            "Windwalker",
            "Wingglide",
            "Wintermoon",
            "Wolfspeak",
            "Yrauos",
        ];

        $dwarven_last = [
            "Axe",
            "Coaldelver",
            "Deepgrip",
            "Flintcoat",
            "Hardchin",
            "Keghood",
            "Minebrow",
            "Runebreaker",
        ];

        # Females

        foreach ($human_females as $name) {
            Name::create([
                'name' => $name,
                'species' => 'human',
                'gender' => 'female',
            ]);
        }

        foreach ($elven_females as $name) {
            Name::create([
                'name' => $name,
                'species' => 'elf',
                'gender' => 'female',
            ]);
        }

        foreach ($dwarven_females as $name) {
            Name::create([
                'name' => $name,
                'species' => 'dwarf',
                'gender' => 'female',
            ]);
        }

        # Males

        foreach ($human_males as $name) {
            Name::create([
                'name' => $name,
                'species' => 'human',
                'gender' => 'male',
            ]);
        }

        foreach ($elven_males as $name) {
            Name::create([
                'name' => $name,
                'species' => 'elf',
                'gender' => 'male',
            ]);
        }

        foreach ($dwarven_males as $name) {
            Name::create([
                'name' => $name,
                'species' => 'dwarf',
                'gender' => 'male',
            ]);
        }

        # NBs

        foreach ($human_nbs as $name) {
            Name::create([
                'name' => $name,
                'species' => 'human',
                'gender' => 'non-binary',
            ]);
        }

        foreach ($elven_nbs as $name) {
            Name::create([
                'name' => $name,
                'species' => 'elf',
                'gender' => 'non-binary',
            ]);
        }

        foreach ($dwarven_nbs as $name) {
            Name::create([
                'name' => $name,
                'species' => 'dwarf',
                'gender' => 'non-binary',
            ]);
        }

        # Last Names

        foreach ($human_last as $name) {
            Name::create([
                'name' => $name,
                'species' => 'human',
            ]);
        }

        foreach ($elven_last as $name) {
            Name::create([
                'name' => $name,
                'species' => 'elf',
            ]);
        }

        foreach ($dwarven_last as $name) {
            Name::create([
                'name' => $name,
                'species' => 'dwarf',
            ]);
        }
    }
}
